version: '3'

services:
  webserver:
    build: 
      context: ./webserver
    container_name: 'webserver'
    restart: 'unless-stopped'
    ports:
      - '8080:80'
      - '443:443'
    volumes: 
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
      